export const site = {
  name: 'Sharayah Hefner',
  origin: 'https://sharayahdesigns.com',
  title: 'Frontend UX Engineer & Design Engineer',
  email: 'SharayahDesigns@gmail.com',
  socialImage: '/images/shareImage.png',
  socialImageAlt: 'Sharayah Hefner portfolio preview',
}

export const routes = [
  {
    path: '/',
    title: 'Sharayah Hefner - Frontend UX Engineer & Design Engineer',
    description: 'Frontend UX Engineer and Design Engineer specializing in React, Next.js, e-commerce, design systems, interaction design, and polished production experiences.',
    type: 'website',
    image: '/images/shareImage.png',
    imageAlt: 'Sharayah Hefner portfolio preview',
    sourceFile: 'src/App.tsx',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'ProfilePage',
      name: 'Sharayah Hefner',
      description: 'Frontend UX Engineer and Design Engineer specializing in React, Next.js, e-commerce, design systems, interaction design, and polished production experiences.',
      url: 'https://sharayahdesigns.com/',
      mainEntity: {
        '@type': 'Person',
        name: 'Sharayah Hefner',
        jobTitle: 'Frontend UX Engineer & Design Engineer',
        url: 'https://sharayahdesigns.com',
        email: 'mailto:SharayahDesigns@gmail.com',
        address: {
          '@type': 'PostalAddress',
          addressLocality: 'Herriman',
          addressRegion: 'Utah',
          addressCountry: 'US',
        },
        alumniOf: 'Southern New Hampshire University',
        knowsAbout: ['React', 'Next.js', 'TypeScript', 'UX Design', 'Design Systems', 'E-Commerce', 'Frontend Development', 'Accessibility', 'Animation'],
        sameAs: [
          'https://github.com/sharayahDesigns',
          'https://linkedin.com/in/SharayahHefner',
        ],
      },
    },
  },
  {
    path: '/resume',
    title: 'Resume - Sharayah Hefner',
    description: 'Online résumé for Sharayah Hefner, Frontend UX Engineer and Design Engineer. View experience, skills, education, and certifications, or download the PDF.',
    type: 'profile',
    image: '/images/shareImage.png',
    imageAlt: 'Sharayah Hefner portfolio preview',
    sourceFile: 'src/components/ResumePage.tsx',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'ProfilePage',
      name: 'Sharayah Hefner Résumé',
      description: 'Online résumé for Sharayah Hefner, Frontend UX Engineer and Design Engineer.',
      url: 'https://sharayahdesigns.com/resume',
      mainEntity: {
        '@type': 'Person',
        name: 'Sharayah Hefner',
        jobTitle: 'Frontend UX Engineer & Design Engineer',
        url: 'https://sharayahdesigns.com/resume',
        email: 'mailto:SharayahDesigns@gmail.com',
        address: {
          '@type': 'PostalAddress',
          addressLocality: 'Herriman',
          addressRegion: 'Utah',
          addressCountry: 'US',
        },
      },
      subjectOf: {
        '@type': 'DigitalDocument',
        name: 'Sharayah Hefner Résumé',
        url: 'https://sharayahdesigns.com/Sharayah_Hefner_Frontend_UX_Engineer_Resume.pdf',
        encodingFormat: 'application/pdf',
      },
    },
  },
  {
    path: '/work/cabana-filters',
    title: 'Cabana Filters Case Study - Sharayah Hefner',
    description: 'See how Sharayah Hefner approached the UX design and frontend engineering of Cabana Filters.',
    type: 'article',
    image: '/images/cabana.webp',
    imageAlt: 'Cabana Filters storefront homepage showing the hero section and product navigation',
    sourceFile: 'src/data/caseStudies.ts',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'Cabana Filters Case Study',
      description: 'See how Sharayah Hefner approached the UX design and frontend engineering of Cabana Filters.',
      image: 'https://sharayahdesigns.com/images/cabana.webp',
      author: { '@type': 'Person', name: 'Sharayah Hefner', url: 'https://sharayahdesigns.com' },
      mainEntityOfPage: 'https://sharayahdesigns.com/work/cabana-filters',
      about: ['React', 'JavaScript', 'HTML', 'CSS', 'Responsive Design', 'E-Commerce'],
    },
  },
  {
    path: '/work/studioplayer',
    title: 'StudioPlayer Case Study - Sharayah Hefner',
    description: 'See how Sharayah Hefner approached the UX design and frontend engineering of StudioPlayer.',
    type: 'article',
    image: '/images/studioPlayerUXUI.webp',
    imageAlt: 'StudioPlayer dashboard, media library and screen-manager views shown across three displays',
    sourceFile: 'src/data/caseStudies.ts',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'StudioPlayer Case Study',
      description: 'See how Sharayah Hefner approached the UX design and frontend engineering of StudioPlayer.',
      image: 'https://sharayahdesigns.com/images/studioPlayerUXUI.webp',
      author: { '@type': 'Person', name: 'Sharayah Hefner', url: 'https://sharayahdesigns.com' },
      mainEntityOfPage: 'https://sharayahdesigns.com/work/studioplayer',
      about: ['React', 'JavaScript', 'CSS Modules', 'Framer Motion', 'AWS'],
    },
  },
  {
    path: '/work/monnit-software',
    title: 'Monnit Software Case Study - Sharayah Hefner',
    description: 'See how Sharayah Hefner approached the UX redesign of Monnit\'s device setup flow inside the iMonnit software platform.',
    type: 'article',
    image: '/images/monnitSoftware.jpg',
    imageAlt: 'Monnit software interface and device setup workflow screens',
    sourceFile: 'src/data/caseStudies.ts',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'Monnit Software Case Study',
      description: 'See how Sharayah Hefner approached the UX redesign of Monnit\'s device setup flow inside the iMonnit software platform.',
      image: 'https://sharayahdesigns.com/images/monnitSoftware.jpg',
      author: { '@type': 'Person', name: 'Sharayah Hefner', url: 'https://sharayahdesigns.com' },
      mainEntityOfPage: 'https://sharayahdesigns.com/work/monnit-software',
      about: ['Wireframing', 'User Flows', 'UX Design', 'SaaS', 'IoT Software'],
    },
  },
  {
    path: '/work/my-logo-mat',
    title: 'My Logo Mat Case Study - Sharayah Hefner',
    description: 'See how Sharayah Hefner approached the UX design and frontend engineering of My Logo Mat.',
    type: 'article',
    image: '/images/logomat.webp',
    imageAlt: 'My Logo Mat storefront showing the custom mat product experience',
    sourceFile: 'src/data/caseStudies.ts',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'My Logo Mat Case Study',
      description: 'See how Sharayah Hefner approached the UX design and frontend engineering of My Logo Mat.',
      image: 'https://sharayahdesigns.com/images/logomat.webp',
      author: { '@type': 'Person', name: 'Sharayah Hefner', url: 'https://sharayahdesigns.com' },
      mainEntityOfPage: 'https://sharayahdesigns.com/work/my-logo-mat',
      about: ['React', 'JavaScript', 'REST APIs', 'Zakeke', 'PayPal', 'Google Places', 'Cloudflare', 'AWS'],
    },
  },
  {
    path: '/work/concrete-connections-nwa',
    title: 'Concrete Connections NWA Case Study - Sharayah Hefner',
    description: 'See how Sharayah Hefner approached the UX design and frontend engineering of Concrete Connections NWA.',
    type: 'article',
    image: '/images/shareImage.png',
    imageAlt: 'Sharayah Hefner portfolio preview',
    sourceFile: 'src/data/caseStudies.ts',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'Concrete Connections NWA Case Study',
      description: 'See how Sharayah Hefner approached the UX design and frontend engineering of Concrete Connections NWA.',
      image: 'https://sharayahdesigns.com/images/shareImage.png',
      author: { '@type': 'Person', name: 'Sharayah Hefner', url: 'https://sharayahdesigns.com' },
      mainEntityOfPage: 'https://sharayahdesigns.com/work/concrete-connections-nwa',
      about: ['React', 'JavaScript', 'Responsive Design', 'Three.js', 'Technical SEO'],
    },
  },
  {
    path: '/work/barnes-hauling',
    title: 'Barnes Hauling & Disposal Case Study - Sharayah Hefner',
    description: 'See how Sharayah Hefner approached the product design and frontend engineering of Barnes Hauling & Disposal.',
    type: 'article',
    image: '/images/bhanddisposal.webp',
    imageAlt: 'Barnes Hauling & Disposal homepage with dumpster rental hero section',
    sourceFile: 'src/data/caseStudies.ts',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'Barnes Hauling & Disposal Case Study',
      description: 'See how Sharayah Hefner approached the product design and frontend engineering of Barnes Hauling & Disposal.',
      image: 'https://sharayahdesigns.com/images/bhanddisposal.webp',
      author: { '@type': 'Person', name: 'Sharayah Hefner', url: 'https://sharayahdesigns.com' },
      mainEntityOfPage: 'https://sharayahdesigns.com/work/barnes-hauling',
      about: ['Next.js', 'Supabase', 'Vercel', 'Admin Dashboard'],
    },
  },
  {
    path: '/work/atlas-league',
    title: 'Atlas League Case Study - Sharayah Hefner',
    description: 'See how Sharayah Hefner approached the product design and frontend engineering of Atlas League.',
    type: 'article',
    image: '/images/shareImage.png',
    imageAlt: 'Sharayah Hefner portfolio preview',
    sourceFile: 'src/data/caseStudies.ts',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'Atlas League Case Study',
      description: 'See how Sharayah Hefner approached the product design and frontend engineering of Atlas League.',
      image: 'https://sharayahdesigns.com/images/shareImage.png',
      author: { '@type': 'Person', name: 'Sharayah Hefner', url: 'https://sharayahdesigns.com' },
      mainEntityOfPage: 'https://sharayahdesigns.com/work/atlas-league',
      about: ['React', 'JavaScript', 'Game UX', 'Mobile Development'],
    },
  },
]
